### ISSUE TITLE
Profile data structure

### ISSUE THREAD

**Issue by chartgerink** [libscie/libscie-api#1]
Each user creates a unique profile in a local Dat repository, which contains information about that user/scholar. This is comparable to an [ORCID](https://orcid.org), but without any central instance (Dat links are public keys which is _so cool_). 

**NOTE: this is very much work in progress. Use this issue to discuss further.**

<details>
  <summary>v0.1</summary>

```json
{
  title: "Chris",
  type: [ "user" ],
  url: "dat://....", 
  avatar: "avatar.png"
  description: "",
  contact: [],
  affiliations: [],
  follows: [],
  nodes: [ "dat://...+\d", "dat://...+\d"],
  annotations: [],
  tags: []
}
```

```yaml
title: name of the profile
type: [beaker archive type](https://github.com/beakerbrowser/specs/blob/master/proposals/0002-shared-data-layer.md#dat-archives-and-archive-types)
url: the user's own Dat link (always latest version)
avatar: filename of an avatar
description: user description [optional]
contact: array of links to contact the individual [optional]. Includes mailto:, https://twitter.com, etc.
affiliations: user's affiliations, multiple possible [optional]
follows: list of dat:// links to follow. Both versioned (dat://...+\d) and unversioned links are possible
nodes: list of shared dat:// information nodes, all versioned
annotations: list of decentralized annotations (don't know how this would look like yet)
tags: array of user-defined tags
```
</details>

<details>
<summary>v0.1.1</summary>

```json
{
  "url": "dat://....", 
  "handle": "chris",
  "tags": [ "statistics", "metaresearch" ],
  "contact": [{
    "mail": [ "chris@libscie.org", "c.h.j.hartgerink@tilburguniversity.edu" ]
  }],
  "connections": [ "Liberate Science", "Tilburg University", "dat://..." ],
  "type": [ "libscie-user" ],
  "avatar": "/avatar.png",
  "follows": [ "dat://...", "dat://..." ],
  "content": [ "dat://...+\d", "dat://...+\d"],
}
```

## Specifications of parts

```yaml
url: Dat link to user profile (hex based)
handle: Username to create subdomain for
tags: User tags, self identify yourself as a combination of tags
contact: Include ways of contacting, each object in an array being its own JSON object
connections: Any kind of connection the user might want to put in (affiliation, organization, other user's profile; these could serve as portals at some point maybe)
type: Type of profile. This might need to go in the main dat.json
avatar: Link to avatar in the user Dat
follows: Array of Dat folders that are of type libscie-user
content: Array of Dat folders that are of type libscie-content
```
</details>

<details>
 <summary>v0.1.2 (WIP; see discussion)</summary>
See discussion
</details>

# Benefits

These are for my own notetaking but will be extended on at some point.

* Content is linked to the user, not the affiliation. Increases portability over time (but there's a cost associated too!)
* User owns their own public profile (nobody else; problem some people have with the centralized services like ORCID).
* Public key of profile can be used to verify the shared content by that user, ensuring that the deposit occurred by the person who is said to be the author (content needs the user's public key, user's profile needs the content public key)
*

**Comment by chartgerink** [comment]
@jimpick just updated the spec to `v0.1.1` and adjusted a bit. I look forward to hearing your thoughts (I started calling it `content` instead of `nodes` to prevent future confusion!)

My main things are:
* I think `type` would go in `dat.json` instead of the separate `profile.json` (which we could also call `metadata.json` or what not)
* connections could be included as strings or as Dat links, where the Dat links could ultimately be some form of discovery portal. What do you think of this?

**Comment by jimpick** [comment]
We can get some of the fields for free from libfritter:

https://github.com/libscie/libfritter/blob/libscie/schemas/profile.json

It looks like there is:

* name
* bio
* avatar
* follows (array of urls and names)

**Comment by chartgerink** [comment]
Thanks @jimpick; that's really helpful. Specifying it as a schema here and in #2. Would be really good if we could specify `dat://...+\d` in the content as mandatory and optional in follows.

```json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "type": "object",
  "properties": {
    "name": {"type": ["null", "string"]},
    "bio": {"type": ["null", "string"]},
    "avatar": {"type": ["null", "string"]},
    "follows": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "url": {"type": "string", "format": "uri"},
          "name": {"type": ["null", "string"]}
        },
    "content": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "url": {"type": "string", "format": "uri"},
          "name": {"type": ["null", "string"]}
        },
        "required": ["url"]
      }
    }
  }
}```

**Comment by chartgerink** [comment]
# v0.1.2 (WIP)

```json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "type": "object",
  "properties": {
    "type": {"type": "string"},
    "url": {"type": "string", "pattern": "dat:\/\/\w{64}"},
    "name": {"type": ["null", "string"]},
    "avatar": {"type": ["null", "string"]},
    "follows": {"type": ["null", "array"], "pattern": "dat:\/\/\w{64}(\+\d+)?"},
    "content": {"type": ["null", "array"], "pattern": "dat:\/\/\w{64}(\+\d+)"}
  },
  "required": ["type", "url"]
}
```

```yaml
type: Object that indicates type of profile and version
url: Dat url (regex: dat:\/\/\w{64})
name: Name of user, string
avatar: filepath to avatar image
follows: array of Dat urls (possibly versioned; dat:\/\/\w{64}(\+\d+)?)
content: array of versioned Dat urls (regex: dat:\/\/\w{64}(\+\d+))
```

Add to schema in later versions

- [ ] `description`: string that serves as a user description
- [ ] `tags`: array of strings that can be used to find connections between users and other users/content
- [ ] `connections`: array of objects that indicate connections to organizations, collectives, institutions etc
- [ ] `contact`: array of objects that indicate communication means that the user can specify
