### ISSUE TITLE
Entry data structure

### ISSUE THREAD

**Issue by chartgerink** [libscie/libscie-api#2]
Each shared piece of information gets stored in its own Dat repository and gets its own public key (i.e., Dat link). It needs to contain metadata and the actual content (how to structure the content is a discussion in ADD ISSUE). These nodes can be continuously updated and only get registered in the profile when a user chooses to. Once shared, other people can look at the latest version if they choose to do so (if they're using the Dat protocol).

**NOTE: this is very much work in progress. Use this issue to discuss further.**

<details>
<summary>v0.1</summary>

```json
{
  title: "",
  type: [ "node" ],
  url: "dat://....", 
  parent: ["dat://...+\d"],
  avatar: "avatar.png"
  contributors: ["dat://....+X", "dat://....+X"],
  description: "DESCRIPTION",
  tags: [],
  main: "index.md"
}
```

## Specifications of parts

```yaml
title: character string of title
type: beaker browser archive type
url: public key of node
parent: array of direct versioned parent nodes, need to precede the current version to ensure chronology
avatar: node picture for display in the network [optional]
contributors: array of contributor public keys
description: character string of description
tags: array of user-defined tags
main: indicates the main file in the Dat repo (helps trawl the nodes and index types)
```
</summary>

# Benefits

* Parent nodes ensure chronology and embed for example preregistration in the communication process (instead of duct-taping it to a publication)
* lineage of findings
* granular contributing (authors can now specifically get recognized for parts)
* granular splits (replications do not need to rehash theory and predictions and methods, but just add a node of data)
